import React from 'react'
import Head from 'next/head'
import Layout from '@components/Layout'
import { FiHome } from 'react-icons/fi'
import { NavbarProps } from '@components/Navbar'

export default function Home() {
  const meta: NavbarProps = {
    title: 'Home',
    icon: <FiHome />,
  }

  return (
    <div className="">
      <Head>
        <title>{meta.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout navbarProps={meta}>ini home</Layout>
    </div>
  )
}
