import React, { useState } from 'react'
import Head from 'next/head'
import Layout from '@components/Layout'
import Login from '@components/Login'
import { FiHome } from 'react-icons/fi'
import { NavbarProps } from '@components/Navbar'
import { Modal } from '@components/Modal'
import { Table, TableBody, TableHeader } from '@components/Table'

export default function Home() {
  const [authorized, setAuthorized] = useState(true)
  const [isOpen, setIsOpen] = useState(false)
  const meta: NavbarProps = {
    title: 'Home',
    icon: <FiHome />,
  }

  return authorized ? (
    <div className="">
      <Head>
        <title>{meta.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout navbarProps={meta}>
        Ini home
        <div>
          <div className="btn btn-primary" onClick={() => setIsOpen(!isOpen)}>
            ini modal
          </div>
          <Modal isOpen={isOpen} setIsOpen={setIsOpen}>
            Ini Modal
          </Modal>
          <div className="my-4">
            ini table generic
            <Table zebra>
              <TableHeader cells={dummyThead} />
              <TableBody>
                <tr>
                  <td className="text-center">1</td>
                  <td>1-1111</td>
                  <td>Ini nama akun</td>
                  <td>
                    Lemon drops muffin pie marshmallow bear claw tart. Gummi bears ice cream cake dessert candy oat cake
                    gingerbread donut.{' '}
                  </td>
                  <td className="text-center">Akun</td>
                  <td className="text-center">Neraca</td>
                  <td className="text-center">Debit</td>
                </tr>
                <tr>
                  <td className="text-center">1</td>
                  <td>1-1111</td>
                  <td>Ini nama akun yang rada panjaaaang</td>
                  <td>
                    Lemon drops muffin pie marshmallow bear claw tart. Gummi bears ice cream cake dessert candy oat cake
                    gingerbread donut.{' '}
                  </td>
                  <td className="text-center">Akun</td>
                  <td className="text-center">Neraca</td>
                  <td className="text-center">Debit</td>
                </tr>
                <tr>
                  <td className="text-center">1</td>
                  <td>1-1111</td>
                  <td>Ini nama akun yang rada panjaaaang</td>
                  <td>
                    Lemon drops muffin pie marshmallow bear claw tart. Gummi bears ice cream cake dessert candy oat cake
                    gingerbread donut.{' '}
                  </td>
                  <td className="text-center">Akun</td>
                  <td className="text-center">Neraca</td>
                  <td className="text-center">Debit</td>
                </tr>
                <tr>
                  <td className="text-center">1</td>
                  <td>1-1111</td>
                  <td>Ini nama akun duduuddu lalalala</td>
                  <td>
                    Lemon drops muffin pie marshmallow bear claw tart. Gummi bears ice cream cake dessert candy oat cake
                    gingerbread donut.{' '}
                  </td>
                  <td className="text-center">Akun</td>
                  <td className="text-center">Neraca</td>
                  <td className="text-center">Debit</td>
                </tr>
              </TableBody>
            </Table>
          </div>
        </div>
      </Layout>
    </div>
  ) : (
    <Login />
  )
}

const dummyThead = ['', 'acc no.', 'account name', 'description', 'jenis', 'tipe', 'saldo normal']
